[package]
edition = "2018"
name = "oclock"
version = "0.1.4"
authors = ["Davide Ghilardi <ghilardi.davide@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.8"
Inflector = {version="0.11", default-features=false}

nng = "0.5"
getopts = "0.2"

schedule = "0.1"
itertools = "0.10"

csv = "1.1"
serde = { version ="1.0", features = ["derive"] }
serde_json = "1.0"

ctrlc = { version = "3.1", features = ["termination"] }

[dependencies.oclock_sqlite]
path = "libs/oclock_sqlite"
