[package]
edition = "2018"
name = "oclock"
version = "0.1.4"
authors = ["Davide Ghilardi <ghilardi.davide@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.8"
Inflector = {version="0.11", default-features=false}

nanomsg = "0.7"
getopts = "0.2"

schedule = "0.1"
itertools = "0.10"

csv = "1.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

ctrlc = { version = "3.1", features = ["termination"] }

[dependencies.oclock_sqlite]
path = "libs/oclock_sqlite"
