name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Install minimal stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run tests
      run: cargo test --verbose
